/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("template.kotlin-application-conventions")
}

dependencies {
    implementation(libs.spring.boot.web)
}

